[package]
name = "wmouse"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31"
wayland-protocols = "0.32"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
input = { version = "0.9", features = ["udev"] }
libc = "0.2"
